steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install', '-DskipTests']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/sapler:$COMMIT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/sapler:$COMMIT_SHA']
